export const links = {
  home: "/",
  ourService: "/our-services",
  serviceDetails: "/service-details",
  registerCompany: "/register-company",
  registerForm: "/register-company/:id",
  contactUs: "/contact-us",
  blog: "/blog",
};
export const  corporateFriendlyCountries = [
    "Egypt",
    "Saudi Arabia (KSA)",
    "United Arab Emirates (UAE)",
    "Cyprus",
    "Hong Kong",
    "Jordan",
    "United States",
    "United Kingdom",
    "Singapore",
    "Switzerland",
    "Netherlands",
    "Ireland",
    "Luxembourg",
    "Germany",
    "France",
    "Canada",
    "China",
    "India",
    "Mauritius",
    "Malta",
    "Malaysia",
    "Thailand",
    "Indonesia",
    "South Africa",
    "Turkey",
    "Qatar",
    "Bahrain",
    "Kuwait",
    "Oman",
    "Lebanon",
    "Portugal",
    "Spain",
    "Italy",
    "Australia",
    "New Zealand",
    "Brazil",
    "Mexico"
  ];
  

  