export const links = {
  home: "/",
  ourService: "/our-services",
  serviceDetails: "/service-details",
  registerCompany: "/register-company",
  registerForm: "/register-company/:id",
  contactUs: "/contact-us",
  blog: "/blog",
};
export const corporateFriendlyCountries = [
  "Select Countery",
  "Egypt",
  "Saudi Arabia (KSA)",
  "United Arab Emirates (UAE)",
  "Cyprus",
  "Hong Kong",
  "Jordan",
  "United States",
  "United Kingdom",
  "Singapore",
  "Switzerland",
  "Netherlands",
  "Ireland",
  "Luxembourg",
  "Germany",
  "France",
  "Canada",
  "China",
  "India",
  "Mauritius",
  "Malta",
  "Malaysia",
  "Thailand",
  "Indonesia",
  "South Africa",
  "Turkey",
  "Qatar",
  "Bahrain",
  "Kuwait",
  "Oman",
  "Lebanon",
  "Portugal",
  "Spain",
  "Italy",
  "Australia",
  "New Zealand",
  "Brazil",
  "Mexico",
];

export const homeService = [
  "Privacy & confidentiality",
  "Accounting & Administration",
  "Regulatory compliance",
  "Ease of doing business",
  "Easy residency visa options",
  "Elevation of your brand value",
  "Banking & investment solutions",
  "Freedom of movement of hard currencies",
  "Mitigation of risks & challenges",
  "Continuity of business & legacy",
  "Succession planning & transfer of wealth",
];

export const servicesList = [
  {
    image: "callcenter.png",
    isAdmin: false,
    text: "lorem lorem lorem lorem lorem loerm lokre dksja d ai jhgdl aas;d ns;dj k;d asad",
    title: "title here",
    key: "1",
  },
  {
    image: "callcenter.png",
    isAdmin: false,
    text: "lorem lorem lorem lorem lorem loerm lokre dksja d ai jhgdl aas;d ns;dj k;d asad",
    title: "title here",
    key: "2",
  },
  {
    image: "callcenter.png",
    isAdmin: false,
    text: "lorem lorem lorem lorem lorem loerm lokre dksja d ai jhgdl aas;d ns;dj k;d asad",
    title: "title here",
    key: "3",
  },
  {
    image: "callcenter.png",
    isAdmin: false,
    text: "lorem lorem lorem lorem lorem loerm lokre dksja d ai jhgdl aas;d ns;dj k;d asad",
    title: "title here",
    key: "4",
  },
  {
    image: "callcenter.png",
    isAdmin: false,
    text: "lorem lorem lorem lorem lorem loerm lokre dksja d ai jhgdl aas;d ns;dj k;d asad",
    title: "title here",
    key: "5",
  },
  {
    image: "callcenter.png",
    isAdmin: false,
    text: "lorem lorem lorem lorem lorem loerm lokre dksja d ai jhgdl aas;d ns;dj k;d asad",
    title: "title here",
    key: "6",
  },
];
